import oracledb
import os
from dotenv import load_dotenv

load_dotenv()

conn = oracledb.connect(
    user=os.getenv('oracle_user'),
    password=os.getenv('oracle_password'),
    dsn=os.getenv('oracle_dsn')
)
cursor = conn.cursor()

# 테이블 생성 (Oracle 문법)
cursor.execute('''
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE posts (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR2(100) NOT NULL,
            title VARCHAR2(200) NOT NULL,
            content CLOB NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
''')

# 샘플 데이터 추가
cursor.execute(
    "INSERT INTO posts (username, title, content) VALUES (:1, :2, :3)",
    ("테스트유저", "테스트제목", "테스트내용")
)
conn.commit()

# 정상적으로 들어갔는지 select로 확인
cursor.execute("SELECT * FROM posts ORDER BY id DESC FETCH FIRST 1 ROWS ONLY")
row = cursor.fetchone()
print("추가된 row:", row)

conn.close()