import oracledb
import os
from dotenv import load_dotenv

load_dotenv()

conn = oracledb.connect(
    user=os.getenv('oracle_user'),
    password=os.getenv('oracle_password'),
    dsn=os.getenv('oracle_dsn'),
    config_dir=os.getenv('oracle_wallet_dir'),      # wallet 경로 추가
    wallet_location=os.getenv('oracle_wallet_dir')  # wallet 경로 추가
)
cursor = conn.cursor()

# posts 테이블 생성
try:
    cursor.execute("""
        CREATE TABLE posts (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR2(100) NOT NULL,
            title VARCHAR2(200) NOT NULL,
            content CLOB NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    print("posts 테이블 생성 완료")
except oracledb.DatabaseError as e:
    if 'ORA-00955' in str(e):  # 이미 테이블이 있으면 무시
        print("posts 테이블이 이미 존재합니다.")
    else:
        raise

conn.close()